workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
    - if: $CI_MERGE_REQUEST_IID && $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    - when: never

default:
  tags:
    - pressure::medium
stages:
  - build

Build:
  stage: build
  image: gitlab.kateops.com/infrastructure/dependency_proxy/containers/golang:1.21

  before_script:
    - cd .kapigen
  script:
    - kapigen generate pipeline -v
  artifacts:
    paths:
      - pipeline.yaml

Trigger Build:
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: pipeline.yaml
        job: Build

    forward:
      pipeline_variables: true
