workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
    - if: $CI_MERGE_REQUEST_IID && $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - when: never
variables:
  KAPIGEN_VERSION: latest
  KAPIGEN_DEFAULT_RUNNER_TAG: pressure:medium
default:
  tags:
    - ${KAPIGEN_DEFAULT_RUNNER_TAG}
stages:
  - build
  - trigger
  - collect

Build:
  stage: build
  image:
    name: registry.gitlab.com/kateops/kapigen/cli:${KAPIGEN_VERSION}
    entrypoint: [""]
  script:
    - kapigen pipeline generate -v  --mode gitlab
  artifacts:
    paths:
      - pipeline.yaml

Trigger Build:
  stage: trigger
  trigger:
    strategy: depend
    include:
      - artifact: pipeline.yaml
        job: Build

    forward:
      pipeline_variables: true



Reports - Junit:
  stage: collect
  allow_failure: true
  when: always
  image:
    name: registry.gitlab.com/kateops/kapigen/cli:${KAPIGEN_VERSION}
    entrypoint: [""]
  script:
    - kapigen pipeline reports -v
  coverage: "/INFO:.+: ([0-9.]+)/"
  artifacts:
    reports:
      junit: '**/*.xml'