pipelines:
  - type: docker
    path: one
    id: five
    config:
      destination: test
      path: cli
  - type: infrastructure
    config:
      state: state-four
      s3: true
    id: four
    path: four