noop: true
versioning: true
dependencyProxy: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
privateTokenName: CI_PIPELINE_TOKEN
tags:
  - ${KAPIGEN_DEFAULT_RUNNER_TAG}
pipelines:
  - type: golang
    id: cli-golang
    config:
      path: cli
      coverage:
        packages:
          - kapigen.kateops.com/internal/...
      imageName: '${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.21.3-alpine3.18'
  - type: docker
    id: cli-docker
    config:
      path: .
      context: .
      name: cli
    needs:
      - cli-golang
