noop: true
tag: true
pipelines:
  - type: golang
    id: cli
    config:
      path: cli
      name: cli
      coverage:
        packages:
          - kapigen.kateops.com/internal/...
      imageName: '${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.21.3-alpine3.18'
      docker:
        path: cli
        release: true
