services:
  app:
    image: golang:1.21
    command: go run . pipeline generate -v --config test.kapigen.yaml
    working_dir: /app/cli
    environment:
      GOMODCACHE: /app/cli/.pkg
      GOCACHE: /app/cli/.cache
      ENVIRONMENT: DEV
    volumes:
      - ../:/app