version: "3.7"
services:
  app:
    image: golang:1.21
    command: go run . generate pipeline -v --config test.kapigen.yaml
    env_file: .env
    working_dir: /app/cli
    environment:
      GOMODCACHE: /app/.pkg
      GOCACHE: /app/.cache
      ENVIRONMENT: DEV
    volumes:
      - .:/app/cli
  register:
    image: gitlab/gitlab-runner:latest
    command: 'run'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../config:/etc/gitlab-runner