pipelines:
  - type: docker
    id: five
    config:
      path: cli
      name: test-cli
  - type: docker
    id: five
    config:
      path: cli
      name: test-cli
  - type: docker
    id: five
    config:
      path: cli
      name: test-cli
      context: test
