pipelines:
  - type: infrastructure
    config:
      #state:
      s3: true
    id: one
  - type: docker
    id: two
    config:
      path: "cli"
      context: "cli"
  - type: infrastructure
    config:
      state: state-name
     # s3: true
    id: three