noop: true
tag: false
pipelines:
  - type: docker
    id: test-cli
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      name: test-cli
  - type: docker
    id: test-file
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      name: test-file
  - type: docker
    id: duplicate-test
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      dockerfile: Dockerfile
      name: test-cli
  - type: golang
    id: test-go
    config:
      imageName: '${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.21.3-alpine3.18'
      path: cli
      docker:
        path: cli
        name: test-file
  - type: docker
    id: test-cli2
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      name: test-cli
  - type: docker
    id: test-file2
    config:
      path: cli
      name: test-file
  - type: docker
    id: duplicate-test2
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      dockerfile: Dockerfile
      name: test-cli
  - type: golang
    id: test-go2
    config:
      imageName: '${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.21.3-alpine3.18'
      path: cli
      docker:
        path: cli
        name: test-file
  - type: docker
    id: test-cli3
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      name: test-cli
  - type: docker
    id: test-file3
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      name: test-file
  - type: docker
    id: duplicate-test3
    tags:
      - saas-linux-medium-amd64
    config:
      path: cli
      dockerfile: Dockerfile
      name: test-cli
  - type: golang
    id: test-go3
    tags:
      - saas-linux-medium-amd64
    config:
      imageName: '${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.21.3-alpine3.18'
      path: cli
      coverage:
        packages:
          - ./...
      docker:
        path: cli
        name: test-file