pipelines:
  - type: docker
    id: test-cli
    config:
      path: cli/tests/docker
      name: test-cli
  - type: docker
    id: test-file
    config:
      path: cli/tests/docker
      name: test-file
  - type: docker
    id: duplicate-test
    config:
      path: cli/tests/docker
      dockerfile: Dockerfile
      name: test-cli
